### PR TITLE
Fix #215: Add a contact page

### LINKED ISSUE #215: Contact page
We should add a contact page pointing people to email addresses, Discourse, IRC, bios about us, etc.

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by spasovski** [comment]
Looks good r+

**Comment by openjck** [comment]
Thanks! I'm going to make some content updates as requested by the team but I won't bother you for another review.

**Comment by spasovski** [comment]
Just a heads-up this will need the CSS moved to its relevant `.styl` file.

**Comment by openjck** [comment]
No problem. Thanks for the heads up!

**Comment by openjck** [comment]
@spasovski Let's merge your Stylus change first, then I'll update this accordingly.

**Comment by openjck** [comment]
I ended up making some adjustments and pushing them straight to master with ccc4d512fda8b7a364fc9b0be372e88396849f88 given that this already got an r+. Thanks for the review!

**Pull request closed without merging**
